# Generated by Django 5.1.4 on 2025-01-02 23:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка на канал, на который надо подписаться')),
                ('reward', models.FloatField(default=0, verbose_name='Награда за задание')),
                ('is_first_task', models.BooleanField(default=False, verbose_name='Явяляется ли это задание необходимым для входа в бота?')),
            ],
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(default=datetime.datetime(2025, 1, 3, 23, 8, 32, 902419, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания задачи')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_task', to='app.task', verbose_name='Задача')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=64, verbose_name='Id пользователя')),
                ('username', models.CharField(max_length=128, verbose_name='Ник пользователя')),
                ('referral_count', models.IntegerField(default=0, verbose_name='Количество рефералов за все время')),
                ('referral_per_day', models.IntegerField(default=0, verbose_name='Рефералы за день')),
                ('balance', models.FloatField(default=0, verbose_name='Баланс пользователя')),
                ('freeze_balance', models.FloatField(default=0, verbose_name='Замороженный баланс пользователя')),
                ('complete_first_task', models.BooleanField(default=False, verbose_name='Подписался ли на первые каналы?')),
                ('referral', models.ManyToManyField(blank=True, to='app.user', verbose_name='Рефералы')),
                ('tasks', models.ManyToManyField(blank=True, to='app.usertask', verbose_name='Задания пользователя')),
            ],
        ),
    ]
