# Generated by Django 5.1.4 on 2025-01-02 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='channel_id',
            field=models.CharField(default=1, max_length=128, verbose_name='ID канала'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertask',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 23, 13, 53, 955154, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания задачи'),
        ),
    ]
