# Generated by Django 5.1.4 on 2025-01-03 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_refferal_reward_user_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 4, 15, 55, 30, 389067, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания задачи'),
        ),
    ]
