# Generated by Django 5.1.4 on 2025-01-04 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_usertask_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.IntegerField(default=10, verbose_name='Награда')),
                ('min_referral', models.IntegerField(default=5, verbose_name='Минимальное количество рефералов в день.')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='use_day_bonus',
            field=models.BooleanField(default=False, verbose_name='Использовал ли дневной бонус?'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 5, 18, 31, 44, 333097, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания задачи'),
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название промокода')),
                ('reward', models.IntegerField(default=10, verbose_name='Награда за промокод')),
                ('max_user', models.IntegerField(default=100, verbose_name='Количество использований')),
                ('min_referral', models.IntegerField(default=0, verbose_name='Минимальное количество рефералов')),
                ('users', models.ManyToManyField(to='app.user', verbose_name='Пользователи, использовавшие промокод')),
            ],
        ),
    ]
