# Generated by Django 5.1.4 on 2025-01-04 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_dayreward_reward_alter_usertask_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayreward',
            name='reward',
            field=models.FloatField(default=1.5, verbose_name='Награда'),
        ),
        migrations.AlterField(
            model_name='refferal_reward',
            name='reward',
            field=models.FloatField(default=2, verbose_name='Награда за реферала'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 5, 19, 25, 38, 300549, tzinfo=datetime.timezone.utc), verbose_name='Дата окончания задачи'),
        ),
    ]
